/*
Script generated by Aqua Data Studio 19.0.1-5 on oct-02-2023 09:53:42 AM
Database: mdn3
Schema: <All Schemas>
Objects: TABLE
*/
ALTER TABLE "informix".tutores
	DROP CONSTRAINT ( r123_98 ) ;
ALTER TABLE "informix".pagos
	DROP CONSTRAINT ( r133_128 ) ;
ALTER TABLE "informix".conducta
	DROP CONSTRAINT ( r129_116 ) ;
ALTER TABLE "informix".asistencia
	DROP CONSTRAINT ( r128_113 ) ;
ALTER TABLE "informix".asignaciones
	DROP CONSTRAINT ( r137_147 ) ;
ALTER TABLE "informix".asignaciones
	DROP CONSTRAINT ( r137_146 ) ;
ALTER TABLE "informix".asignaciones
	DROP CONSTRAINT ( r137_145 ) ;
ALTER TABLE "informix".asignaciones
	DROP CONSTRAINT ( r137_144 ) ;
ALTER TABLE "informix".actividades
	DROP CONSTRAINT ( r136_141 ) ;
ALTER TABLE "informix".actividades
	DROP CONSTRAINT ( r136_140 ) ;
ALTER TABLE "informix".actividades
	DROP CONSTRAINT ( r136_139 ) ;
ALTER TABLE "informix".usuarios
	DROP CONSTRAINT ( c132_126 ) ;
DROP TABLE "informix".usuarios;
DROP TABLE "informix".tutores;
DROP TABLE "informix".secciones;
DROP TABLE "informix".profesores;
DROP TABLE "informix".pagos;
DROP TABLE "informix".grados;
DROP TABLE "informix".conducta;
DROP TABLE "informix".asistencia;
DROP TABLE "informix".asignaciones;
DROP TABLE "informix".alumnos;
DROP TABLE "informix".actividades;

CREATE TABLE "informix".actividades  ( 
	actividad_id         	SERIAL NOT NULL,
	actividad_profesor   	INTEGER,
	actividad_grado      	INTEGER,
	actividad_seccion    	INTEGER,
	actividad_fecha_inicio	DATETIME YEAR to MINUTE,
	actividad_fecha_fin  	DATETIME YEAR to MINUTE,
	actividad_descripcion	VARCHAR(255),
	actividad_situacion  	INTEGER DEFAULT 1,
	PRIMARY KEY(actividad_id)
	ENABLED
)
LOCK MODE ROW;
CREATE TABLE "informix".alumnos  ( 
	alumno_id              	SERIAL NOT NULL,
	alumno_nombre          	VARCHAR(255),
	alumno_edad            	INTEGER,
	alumno_sexo            	CHAR(1),
	alumno_fecha_nacimiento	DATETIME YEAR to DAY,
	alumno_situacion       	INTEGER DEFAULT 1,
	PRIMARY KEY(alumno_id)
	ENABLED
)
LOCK MODE ROW;
CREATE TABLE "informix".asignaciones  ( 
	asignacion_id       	SERIAL NOT NULL,
	asignacion_alumno   	INTEGER,
	asignacion_profesor 	INTEGER,
	asignacion_grado    	INTEGER,
	asignacion_seccion  	INTEGER,
	asignacion_situacion	INTEGER DEFAULT 1,
	PRIMARY KEY(asignacion_id)
	ENABLED
)
LOCK MODE ROW;
CREATE TABLE "informix".asistencia  ( 
	asistencia_id       	SERIAL NOT NULL,
	alumno_id           	INTEGER,
	asistencia_fecha    	DATETIME YEAR to DAY,
	asistencia_asistio  	VARCHAR(15),
	asistencia_situacion	INTEGER DEFAULT 1,
	PRIMARY KEY(asistencia_id)
	ENABLED
)
LOCK MODE ROW;
CREATE TABLE "informix".conducta  ( 
	conducta_id         	SERIAL NOT NULL,
	alumno_id           	INTEGER,
	conducta_fecha      	DATETIME YEAR to DAY,
	conducta_descripcion	VARCHAR(255),
	conducta_situacion  	INTEGER DEFAULT 1,
	PRIMARY KEY(conducta_id)
	ENABLED
)
LOCK MODE ROW;
CREATE TABLE "informix".grados  ( 
	grado_id       	SERIAL NOT NULL,
	grado_nombre   	VARCHAR(50),
	grado_situacion	INTEGER DEFAULT 1,
	PRIMARY KEY(grado_id)
	ENABLED
)
LOCK MODE ROW;
CREATE TABLE "informix".pagos  ( 
	pago_id       	SERIAL NOT NULL,
	pago_alumno_id	INTEGER,
	pago_fecha    	DATETIME YEAR to DAY,
	pago_mes      	INTEGER,
	pago_monto    	DECIMAL(10,2),
	pago_solvencia	CHAR(2),
	pago_situacion	INTEGER DEFAULT 1,
	PRIMARY KEY(pago_id)
	ENABLED
)
LOCK MODE ROW;
CREATE TABLE "informix".profesores  ( 
	profesor_id       	SERIAL NOT NULL,
	profesor_nombre   	VARCHAR(255),
	profesor_telefono 	VARCHAR(15),
	profesor_situacion	INTEGER DEFAULT 1,
	PRIMARY KEY(profesor_id)
	ENABLED
)
LOCK MODE ROW;
CREATE TABLE "informix".secciones  ( 
	seccion_id       	SERIAL NOT NULL,
	seccion_nombre   	VARCHAR(50),
	seccion_situacion	INTEGER DEFAULT 1,
	PRIMARY KEY(seccion_id)
	ENABLED
)
LOCK MODE ROW;
CREATE TABLE "informix".tutores  ( 
	tutor_id       	SERIAL NOT NULL,
	tutor_nombre   	VARCHAR(255),
	tutor_telefono 	VARCHAR(15),
	tutor_parentezco	VARCHAR(255),
	alumno_id      	INTEGER,
	tutor_situacion	INTEGER DEFAULT 1,
	PRIMARY KEY(tutor_id)
	ENABLED
)
LOCK MODE ROW;
CREATE TABLE "informix".usuarios  ( 
	usuario_id       	SERIAL NOT NULL,
	usuario_nombre   	VARCHAR(50),
	usuario_password 	LVARCHAR(2048),
	usuario_tipo     	VARCHAR(20),
	usuario_situacion	INTEGER DEFAULT 1,
	PRIMARY KEY(usuario_id)
	ENABLED
)
LOCK MODE ROW;

ALTER TABLE "informix".usuarios
	ADD CONSTRAINT ( CHECK (usuario_tipo IN ('ALUMNO' ,'TUTOR' ,'ADMINISTRADOR' )) CONSTRAINT c132_126
	ENABLED );
ALTER TABLE "informix".actividades
	ADD CONSTRAINT ( FOREIGN KEY(actividad_seccion)
	REFERENCES "informix".secciones(seccion_id) CONSTRAINT r136_141
	ENABLED );
ALTER TABLE "informix".actividades
	ADD CONSTRAINT ( FOREIGN KEY(actividad_grado)
	REFERENCES "informix".grados(grado_id) CONSTRAINT r136_140
	ENABLED );
ALTER TABLE "informix".actividades
	ADD CONSTRAINT ( FOREIGN KEY(actividad_profesor)
	REFERENCES "informix".profesores(profesor_id) CONSTRAINT r136_139
	ENABLED );
ALTER TABLE "informix".asignaciones
	ADD CONSTRAINT ( FOREIGN KEY(asignacion_seccion)
	REFERENCES "informix".secciones(seccion_id) CONSTRAINT r137_147
	ENABLED );
ALTER TABLE "informix".asignaciones
	ADD CONSTRAINT ( FOREIGN KEY(asignacion_grado)
	REFERENCES "informix".grados(grado_id) CONSTRAINT r137_146
	ENABLED );
ALTER TABLE "informix".asignaciones
	ADD CONSTRAINT ( FOREIGN KEY(asignacion_profesor)
	REFERENCES "informix".profesores(profesor_id) CONSTRAINT r137_145
	ENABLED );
ALTER TABLE "informix".asignaciones
	ADD CONSTRAINT ( FOREIGN KEY(asignacion_alumno)
	REFERENCES "informix".alumnos(alumno_id) CONSTRAINT r137_144
	ENABLED );
ALTER TABLE "informix".asistencia
	ADD CONSTRAINT ( FOREIGN KEY(alumno_id)
	REFERENCES "informix".alumnos(alumno_id) CONSTRAINT r128_113
	ENABLED );
ALTER TABLE "informix".conducta
	ADD CONSTRAINT ( FOREIGN KEY(alumno_id)
	REFERENCES "informix".alumnos(alumno_id) CONSTRAINT r129_116
	ENABLED );
ALTER TABLE "informix".pagos
	ADD CONSTRAINT ( FOREIGN KEY(pago_alumno_id)
	REFERENCES "informix".alumnos(alumno_id) CONSTRAINT r133_128
	ENABLED );
ALTER TABLE "informix".tutores
	ADD CONSTRAINT ( FOREIGN KEY(alumno_id)
	REFERENCES "informix".alumnos(alumno_id) CONSTRAINT r123_98
	ENABLED );
GRANT SELECT, INSERT, UPDATE, DELETE, INDEX ON "informix".actividades TO "public";
GRANT SELECT, INSERT, UPDATE, DELETE, INDEX ON "informix".alumnos TO "public";
GRANT SELECT, INSERT, UPDATE, DELETE, INDEX ON "informix".asignaciones TO "public";
GRANT SELECT, INSERT, UPDATE, DELETE, INDEX ON "informix".asistencia TO "public";
GRANT SELECT, INSERT, UPDATE, DELETE, INDEX ON "informix".conducta TO "public";
GRANT SELECT, INSERT, UPDATE, DELETE, INDEX ON "informix".grados TO "public";
GRANT SELECT, INSERT, UPDATE, DELETE, INDEX ON "informix".pagos TO "public";
GRANT SELECT, INSERT, UPDATE, DELETE, INDEX ON "informix".profesores TO "public";
GRANT SELECT, INSERT, UPDATE, DELETE, INDEX ON "informix".secciones TO "public";
GRANT SELECT, INSERT, UPDATE, DELETE, INDEX ON "informix".tutores TO "public";
GRANT SELECT, INSERT, UPDATE, DELETE, INDEX ON "informix".usuarios TO "public";
